// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/raydatray/fluffy-octo-fishstick/boxes/server/ent/course"
	"github.com/raydatray/fluffy-octo-fishstick/boxes/server/ent/coursesection"
	"github.com/raydatray/fluffy-octo-fishstick/boxes/server/ent/user"
)

// CourseSectionCreate is the builder for creating a CourseSection entity.
type CourseSectionCreate struct {
	config
	mutation *CourseSectionMutation
	hooks    []Hook
}

// SetNumber sets the "number" field.
func (_c *CourseSectionCreate) SetNumber(v int) *CourseSectionCreate {
	_c.mutation.SetNumber(v)
	return _c
}

// SetCourseID sets the "course" edge to the Course entity by ID.
func (_c *CourseSectionCreate) SetCourseID(id int) *CourseSectionCreate {
	_c.mutation.SetCourseID(id)
	return _c
}

// SetCourse sets the "course" edge to the Course entity.
func (_c *CourseSectionCreate) SetCourse(v *Course) *CourseSectionCreate {
	return _c.SetCourseID(v.ID)
}

// AddProfessorIDs adds the "professors" edge to the User entity by IDs.
func (_c *CourseSectionCreate) AddProfessorIDs(ids ...int) *CourseSectionCreate {
	_c.mutation.AddProfessorIDs(ids...)
	return _c
}

// AddProfessors adds the "professors" edges to the User entity.
func (_c *CourseSectionCreate) AddProfessors(v ...*User) *CourseSectionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddProfessorIDs(ids...)
}

// AddTeachingAssistantIDs adds the "teaching_assistants" edge to the User entity by IDs.
func (_c *CourseSectionCreate) AddTeachingAssistantIDs(ids ...int) *CourseSectionCreate {
	_c.mutation.AddTeachingAssistantIDs(ids...)
	return _c
}

// AddTeachingAssistants adds the "teaching_assistants" edges to the User entity.
func (_c *CourseSectionCreate) AddTeachingAssistants(v ...*User) *CourseSectionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTeachingAssistantIDs(ids...)
}

// AddCourseAssistantIDs adds the "course_assistants" edge to the User entity by IDs.
func (_c *CourseSectionCreate) AddCourseAssistantIDs(ids ...int) *CourseSectionCreate {
	_c.mutation.AddCourseAssistantIDs(ids...)
	return _c
}

// AddCourseAssistants adds the "course_assistants" edges to the User entity.
func (_c *CourseSectionCreate) AddCourseAssistants(v ...*User) *CourseSectionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCourseAssistantIDs(ids...)
}

// AddStudentIDs adds the "students" edge to the User entity by IDs.
func (_c *CourseSectionCreate) AddStudentIDs(ids ...int) *CourseSectionCreate {
	_c.mutation.AddStudentIDs(ids...)
	return _c
}

// AddStudents adds the "students" edges to the User entity.
func (_c *CourseSectionCreate) AddStudents(v ...*User) *CourseSectionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddStudentIDs(ids...)
}

// Mutation returns the CourseSectionMutation object of the builder.
func (_c *CourseSectionCreate) Mutation() *CourseSectionMutation {
	return _c.mutation
}

// Save creates the CourseSection in the database.
func (_c *CourseSectionCreate) Save(ctx context.Context) (*CourseSection, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CourseSectionCreate) SaveX(ctx context.Context) *CourseSection {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CourseSectionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CourseSectionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CourseSectionCreate) check() error {
	if _, ok := _c.mutation.Number(); !ok {
		return &ValidationError{Name: "number", err: errors.New(`ent: missing required field "CourseSection.number"`)}
	}
	if len(_c.mutation.CourseIDs()) == 0 {
		return &ValidationError{Name: "course", err: errors.New(`ent: missing required edge "CourseSection.course"`)}
	}
	if len(_c.mutation.ProfessorsIDs()) == 0 {
		return &ValidationError{Name: "professors", err: errors.New(`ent: missing required edge "CourseSection.professors"`)}
	}
	return nil
}

func (_c *CourseSectionCreate) sqlSave(ctx context.Context) (*CourseSection, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CourseSectionCreate) createSpec() (*CourseSection, *sqlgraph.CreateSpec) {
	var (
		_node = &CourseSection{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(coursesection.Table, sqlgraph.NewFieldSpec(coursesection.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Number(); ok {
		_spec.SetField(coursesection.FieldNumber, field.TypeInt, value)
		_node.Number = value
	}
	if nodes := _c.mutation.CourseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   coursesection.CourseTable,
			Columns: []string{coursesection.CourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(course.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.course_sections = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProfessorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   coursesection.ProfessorsTable,
			Columns: coursesection.ProfessorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TeachingAssistantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   coursesection.TeachingAssistantsTable,
			Columns: coursesection.TeachingAssistantsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CourseAssistantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   coursesection.CourseAssistantsTable,
			Columns: coursesection.CourseAssistantsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.StudentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   coursesection.StudentsTable,
			Columns: coursesection.StudentsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CourseSectionCreateBulk is the builder for creating many CourseSection entities in bulk.
type CourseSectionCreateBulk struct {
	config
	err      error
	builders []*CourseSectionCreate
}

// Save creates the CourseSection entities in the database.
func (_c *CourseSectionCreateBulk) Save(ctx context.Context) ([]*CourseSection, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CourseSection, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CourseSectionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CourseSectionCreateBulk) SaveX(ctx context.Context) []*CourseSection {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CourseSectionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CourseSectionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
