// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/raydatray/fluffy-octo-fishstick/boxes/server/ent/discussionboard"
	"github.com/raydatray/fluffy-octo-fishstick/boxes/server/ent/predicate"
)

// DiscussionBoardDelete is the builder for deleting a DiscussionBoard entity.
type DiscussionBoardDelete struct {
	config
	hooks    []Hook
	mutation *DiscussionBoardMutation
}

// Where appends a list predicates to the DiscussionBoardDelete builder.
func (_d *DiscussionBoardDelete) Where(ps ...predicate.DiscussionBoard) *DiscussionBoardDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DiscussionBoardDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DiscussionBoardDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DiscussionBoardDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(discussionboard.Table, sqlgraph.NewFieldSpec(discussionboard.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DiscussionBoardDeleteOne is the builder for deleting a single DiscussionBoard entity.
type DiscussionBoardDeleteOne struct {
	_d *DiscussionBoardDelete
}

// Where appends a list predicates to the DiscussionBoardDelete builder.
func (_d *DiscussionBoardDeleteOne) Where(ps ...predicate.DiscussionBoard) *DiscussionBoardDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DiscussionBoardDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{discussionboard.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DiscussionBoardDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
