// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/raydatray/fluffy-octo-fishstick/boxes/server/ent/course"
	"github.com/raydatray/fluffy-octo-fishstick/boxes/server/ent/discussionboard"
	"github.com/raydatray/fluffy-octo-fishstick/boxes/server/ent/post"
	"github.com/raydatray/fluffy-octo-fishstick/boxes/server/ent/predicate"
)

// DiscussionBoardQuery is the builder for querying DiscussionBoard entities.
type DiscussionBoardQuery struct {
	config
	ctx            *QueryContext
	order          []discussionboard.OrderOption
	inters         []Interceptor
	predicates     []predicate.DiscussionBoard
	withPosts      *PostQuery
	withCourse     *CourseQuery
	withFKs        bool
	modifiers      []func(*sql.Selector)
	loadTotal      []func(context.Context, []*DiscussionBoard) error
	withNamedPosts map[string]*PostQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DiscussionBoardQuery builder.
func (_q *DiscussionBoardQuery) Where(ps ...predicate.DiscussionBoard) *DiscussionBoardQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *DiscussionBoardQuery) Limit(limit int) *DiscussionBoardQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *DiscussionBoardQuery) Offset(offset int) *DiscussionBoardQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *DiscussionBoardQuery) Unique(unique bool) *DiscussionBoardQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *DiscussionBoardQuery) Order(o ...discussionboard.OrderOption) *DiscussionBoardQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryPosts chains the current query on the "posts" edge.
func (_q *DiscussionBoardQuery) QueryPosts() *PostQuery {
	query := (&PostClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(discussionboard.Table, discussionboard.FieldID, selector),
			sqlgraph.To(post.Table, post.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, discussionboard.PostsTable, discussionboard.PostsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCourse chains the current query on the "course" edge.
func (_q *DiscussionBoardQuery) QueryCourse() *CourseQuery {
	query := (&CourseClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(discussionboard.Table, discussionboard.FieldID, selector),
			sqlgraph.To(course.Table, course.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, discussionboard.CourseTable, discussionboard.CourseColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DiscussionBoard entity from the query.
// Returns a *NotFoundError when no DiscussionBoard was found.
func (_q *DiscussionBoardQuery) First(ctx context.Context) (*DiscussionBoard, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{discussionboard.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *DiscussionBoardQuery) FirstX(ctx context.Context) *DiscussionBoard {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DiscussionBoard ID from the query.
// Returns a *NotFoundError when no DiscussionBoard ID was found.
func (_q *DiscussionBoardQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{discussionboard.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *DiscussionBoardQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DiscussionBoard entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DiscussionBoard entity is found.
// Returns a *NotFoundError when no DiscussionBoard entities are found.
func (_q *DiscussionBoardQuery) Only(ctx context.Context) (*DiscussionBoard, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{discussionboard.Label}
	default:
		return nil, &NotSingularError{discussionboard.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *DiscussionBoardQuery) OnlyX(ctx context.Context) *DiscussionBoard {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DiscussionBoard ID in the query.
// Returns a *NotSingularError when more than one DiscussionBoard ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *DiscussionBoardQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{discussionboard.Label}
	default:
		err = &NotSingularError{discussionboard.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *DiscussionBoardQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DiscussionBoards.
func (_q *DiscussionBoardQuery) All(ctx context.Context) ([]*DiscussionBoard, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DiscussionBoard, *DiscussionBoardQuery]()
	return withInterceptors[[]*DiscussionBoard](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *DiscussionBoardQuery) AllX(ctx context.Context) []*DiscussionBoard {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DiscussionBoard IDs.
func (_q *DiscussionBoardQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(discussionboard.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *DiscussionBoardQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *DiscussionBoardQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*DiscussionBoardQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *DiscussionBoardQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *DiscussionBoardQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *DiscussionBoardQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DiscussionBoardQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *DiscussionBoardQuery) Clone() *DiscussionBoardQuery {
	if _q == nil {
		return nil
	}
	return &DiscussionBoardQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]discussionboard.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.DiscussionBoard{}, _q.predicates...),
		withPosts:  _q.withPosts.Clone(),
		withCourse: _q.withCourse.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithPosts tells the query-builder to eager-load the nodes that are connected to
// the "posts" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DiscussionBoardQuery) WithPosts(opts ...func(*PostQuery)) *DiscussionBoardQuery {
	query := (&PostClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPosts = query
	return _q
}

// WithCourse tells the query-builder to eager-load the nodes that are connected to
// the "course" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DiscussionBoardQuery) WithCourse(opts ...func(*CourseQuery)) *DiscussionBoardQuery {
	query := (&CourseClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCourse = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DiscussionBoard.Query().
//		GroupBy(discussionboard.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *DiscussionBoardQuery) GroupBy(field string, fields ...string) *DiscussionBoardGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DiscussionBoardGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = discussionboard.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.DiscussionBoard.Query().
//		Select(discussionboard.FieldName).
//		Scan(ctx, &v)
func (_q *DiscussionBoardQuery) Select(fields ...string) *DiscussionBoardSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &DiscussionBoardSelect{DiscussionBoardQuery: _q}
	sbuild.label = discussionboard.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DiscussionBoardSelect configured with the given aggregations.
func (_q *DiscussionBoardQuery) Aggregate(fns ...AggregateFunc) *DiscussionBoardSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *DiscussionBoardQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !discussionboard.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *DiscussionBoardQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DiscussionBoard, error) {
	var (
		nodes       = []*DiscussionBoard{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withPosts != nil,
			_q.withCourse != nil,
		}
	)
	if _q.withCourse != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, discussionboard.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DiscussionBoard).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DiscussionBoard{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withPosts; query != nil {
		if err := _q.loadPosts(ctx, query, nodes,
			func(n *DiscussionBoard) { n.Edges.Posts = []*Post{} },
			func(n *DiscussionBoard, e *Post) { n.Edges.Posts = append(n.Edges.Posts, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCourse; query != nil {
		if err := _q.loadCourse(ctx, query, nodes, nil,
			func(n *DiscussionBoard, e *Course) { n.Edges.Course = e }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedPosts {
		if err := _q.loadPosts(ctx, query, nodes,
			func(n *DiscussionBoard) { n.appendNamedPosts(name) },
			func(n *DiscussionBoard, e *Post) { n.appendNamedPosts(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *DiscussionBoardQuery) loadPosts(ctx context.Context, query *PostQuery, nodes []*DiscussionBoard, init func(*DiscussionBoard), assign func(*DiscussionBoard, *Post)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*DiscussionBoard)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Post(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(discussionboard.PostsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.discussion_board_posts
		if fk == nil {
			return fmt.Errorf(`foreign-key "discussion_board_posts" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "discussion_board_posts" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *DiscussionBoardQuery) loadCourse(ctx context.Context, query *CourseQuery, nodes []*DiscussionBoard, init func(*DiscussionBoard), assign func(*DiscussionBoard, *Course)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*DiscussionBoard)
	for i := range nodes {
		if nodes[i].course_discussion_board == nil {
			continue
		}
		fk := *nodes[i].course_discussion_board
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(course.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "course_discussion_board" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *DiscussionBoardQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *DiscussionBoardQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(discussionboard.Table, discussionboard.Columns, sqlgraph.NewFieldSpec(discussionboard.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, discussionboard.FieldID)
		for i := range fields {
			if fields[i] != discussionboard.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *DiscussionBoardQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(discussionboard.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = discussionboard.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedPosts tells the query-builder to eager-load the nodes that are connected to the "posts"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *DiscussionBoardQuery) WithNamedPosts(name string, opts ...func(*PostQuery)) *DiscussionBoardQuery {
	query := (&PostClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedPosts == nil {
		_q.withNamedPosts = make(map[string]*PostQuery)
	}
	_q.withNamedPosts[name] = query
	return _q
}

// DiscussionBoardGroupBy is the group-by builder for DiscussionBoard entities.
type DiscussionBoardGroupBy struct {
	selector
	build *DiscussionBoardQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *DiscussionBoardGroupBy) Aggregate(fns ...AggregateFunc) *DiscussionBoardGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *DiscussionBoardGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DiscussionBoardQuery, *DiscussionBoardGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *DiscussionBoardGroupBy) sqlScan(ctx context.Context, root *DiscussionBoardQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DiscussionBoardSelect is the builder for selecting fields of DiscussionBoard entities.
type DiscussionBoardSelect struct {
	*DiscussionBoardQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *DiscussionBoardSelect) Aggregate(fns ...AggregateFunc) *DiscussionBoardSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *DiscussionBoardSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DiscussionBoardQuery, *DiscussionBoardSelect](ctx, _s.DiscussionBoardQuery, _s, _s.inters, v)
}

func (_s *DiscussionBoardSelect) sqlScan(ctx context.Context, root *DiscussionBoardQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
