// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/raydatray/fluffy-octo-fishstick/boxes/server/ent/discussionboard"
	"github.com/raydatray/fluffy-octo-fishstick/boxes/server/ent/post"
	"github.com/raydatray/fluffy-octo-fishstick/boxes/server/ent/reply"
	"github.com/raydatray/fluffy-octo-fishstick/boxes/server/ent/schema"
	"github.com/raydatray/fluffy-octo-fishstick/boxes/server/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	discussionboardFields := schema.DiscussionBoard{}.Fields()
	_ = discussionboardFields
	// discussionboardDescName is the schema descriptor for name field.
	discussionboardDescName := discussionboardFields[0].Descriptor()
	// discussionboard.NameValidator is a validator for the "name" field. It is called by the builders before save.
	discussionboard.NameValidator = discussionboardDescName.Validators[0].(func(string) error)
	postFields := schema.Post{}.Fields()
	_ = postFields
	// postDescTitle is the schema descriptor for title field.
	postDescTitle := postFields[0].Descriptor()
	// post.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	post.TitleValidator = postDescTitle.Validators[0].(func(string) error)
	// postDescContent is the schema descriptor for content field.
	postDescContent := postFields[1].Descriptor()
	// post.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	post.ContentValidator = postDescContent.Validators[0].(func(string) error)
	replyFields := schema.Reply{}.Fields()
	_ = replyFields
	// replyDescContent is the schema descriptor for content field.
	replyDescContent := replyFields[0].Descriptor()
	// reply.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	reply.ContentValidator = replyDescContent.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescFirstName is the schema descriptor for first_name field.
	userDescFirstName := userFields[0].Descriptor()
	// user.FirstNameValidator is a validator for the "first_name" field. It is called by the builders before save.
	user.FirstNameValidator = userDescFirstName.Validators[0].(func(string) error)
	// userDescLastName is the schema descriptor for last_name field.
	userDescLastName := userFields[2].Descriptor()
	// user.LastNameValidator is a validator for the "last_name" field. It is called by the builders before save.
	user.LastNameValidator = userDescLastName.Validators[0].(func(string) error)
}
