// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Course is the predicate function for course builders.
type Course func(*sql.Selector)

// CourseSection is the predicate function for coursesection builders.
type CourseSection func(*sql.Selector)

// DiscussionBoard is the predicate function for discussionboard builders.
type DiscussionBoard func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// Reply is the predicate function for reply builders.
type Reply func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
